### ISSUE TITLE
disable_web_page_preview

### ISSUE THREAD

**Issue by m1kc** [uonline/admiral#1]
https://core.telegram.org/bots/api#sendmessage

![2015-09-01 21-16-18](https://cloud.githubusercontent.com/assets/1831620/9612514/bf8353a2-50ee-11e5-9ed0-c12bac4b105b.png)

**Comment by 3bl3gamer** [comment]
Наверно имелся в виду переключатель? Сейчас превью всегда отрублено, и у меня в экран влезают больше двух сообщений.
