### ISSUE TITLE
All event types

### ISSUE THREAD

**Issue by m1kc** [uonline/admiral#2]
![2015-09-15 15-52-57](https://cloud.githubusercontent.com/assets/1831620/9876898/1ae51e78-5bc2-11e5-9a6e-ce9471a9d964.png)

**Comment by m1kc** [comment]
Документация и примеры здесь: https://developer.github.com/v3/activity/events/types/

**Comment by 3bl3gamer** [comment]
Так, это https://github.com/uonline/admiral/commit/c6f8a07f26d2b51f52ca99afb436bd9996fb2165 сюда.
