### ISSUE TITLE
Юнит-тесты

### ISSUE THREAD

**Issue by m1kc** [uonline/admiral#6]
Если точнее - скрипт, который подключается к адмиралу по HTTP и кидает ему в /hubot/github все примеры из документации.

**Comment by 3bl3gamer** [comment]
Не HTTP, но подключается и примеры кидает https://github.com/uonline/admiral/commit/542a45f7fa7ee6a863b0f9740954c1ef66fbb0c2

**Comment by m1kc** [comment]
Теперь бы неплохо ещё и HTTP как опцию.
